### ISSUE TITLE
Loop calling on a very small chromosome

### ISSUE THREAD

**Issue by liz-is** [ay-lab/mustache#11]
Hello,

I'm interested in running `mustache` on Drosophila Hi-C data. Chromosome 4 in Drosophila is very small, only 1.3 Mb, and `mustache` fails on this chromosome with the error below. 

Is it possible to get this to work with different parameters? What would you suggest?

The size of the region it's trying to extract seems to depend on the resolution, as it was `[0, 8000000)` when I tried this at 4 kb resolution, otherwise my first thought would have been to try changing the distance limit to less than the chromosome size. 

Command I used:
`mustache -f data/hic/cooler_files/wt_Rep1_2kb.mcool -o data/hic/loops/wt_Rep1_2kb_4_mustache_loops_default.tsv -ch 4 -r 2kb -p 4 `

Error:
```
The distance limit is set to 2Mbp
Reading contact map...
Traceback (most recent call last):
  File "/home/research/vaquerizas/liz/project/.venv/lib/python3.8/site-packages/mustache/mustache.py", line 464, in read_mcooler
    temp = clr.matrix(balance=True,sparse=True).fetch( (chr1, int(start), int(end)))
  File "/home/research/vaquerizas/liz/project/.venv/lib/python3.8/site-packages/cooler/core.py", line 573, in fetch
    i0, i1, j0, j1 = self._fetch(*args, **kwargs)
  File "/home/research/vaquerizas/liz/project/.venv/lib/python3.8/site-packages/cooler/api.py", line 384, in _fetch
    region1 = parse_region(region, self._chromsizes)
  File "/home/research/vaquerizas/liz/project/.venv/lib/python3.8/site-packages/cooler/util.py", line 181, in parse_region
    raise ValueError("Genomic region out of bounds: [{}, {})".format(start, end))
ValueError: Genomic region out of bounds: [0, 4000000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/research/vaquerizas/liz/project/.venv/bin/mustache", line 8, in <module>
    sys.exit(main())
  File "/home/research/vaquerizas/liz/project/.venv/lib/python3.8/site-packages/mustache/mustache.py", line 904, in main
    o = regulator(f, args.norm_method, CHRM_SIZE, args.outdir,
  File "/home/research/vaquerizas/liz/project/.venv/lib/python3.8/site-packages/mustache/mustache.py", line 773, in regulator
    x, y, v = read_mcooler(f, distance_in_bp, chromosome,chromosome2, res)
  File "/home/research/vaquerizas/liz/project/.venv/lib/python3.8/site-packages/mustache/mustache.py", line 493, in read_mcooler
    raise NameError('Reading from the file failed!')
NameError: Reading from the file failed!
```

I installed mustache today, if the version is relevant (it might be nice to be able to access the version number with `mustache --version` and/or print it in the log files?)

**Comment by ay-lab** [comment]
Hi, thanks for using our tool. You are right, it's because of the chromosome size. I am working on the code to fix the problem but can you please share the data with me so that I can make sure it's working properly?

**Comment by liz-is** [comment]
I can't share the specific dataset I was using, but you could use [this dataset](https://www.ebi.ac.uk/arrayexpress/files/E-MTAB-4918/E-MTAB-4918.processed.1.zip/Hug2017_3-4h_all_5k.mcool) to test the code - it's also Drosophila Hi-C in .mcool format, at 5kb resolution though.

**Comment by ay-lab** [comment]
OK, the .mcool input file had a weird (or unfamiliar) format and it took me some time to realized that. I fixed the code but didn't have the chance to check the detected loops. Please let me know how it works now.

"cooler ls Hug2017_3-4h_all_5k.mcool" gives:
Hug2017_3-4h_all_5k.mcool::/0
Hug2017_3-4h_all_5k.mcool::/1
Hug2017_3-4h_all_5k.mcool::/2
Hug2017_3-4h_all_5k.mcool::/3
Hug2017_3-4h_all_5k.mcool::/4
Hug2017_3-4h_all_5k.mcool::/5
Hug2017_3-4h_all_5k.mcool::/6
Hug2017_3-4h_all_5k.mcool::/7

**Comment by liz-is** [comment]
Ah, you mean you expect it to specify the resolution in bp? The Hug et al. 2017 file was created a couple of years ago now so I guess that depends on the version of cooler that was used to create the file. I didn't realise this was different, sorry!

The file I was actually using does give the resolutions in bp:

```
data/hic/cooler_files/wt_Rep1_2kb.mcool::/resolutions/2000
data/hic/cooler_files/wt_Rep1_2kb.mcool::/resolutions/4000
data/hic/cooler_files/wt_Rep1_2kb.mcool::/resolutions/8000
data/hic/cooler_files/wt_Rep1_2kb.mcool::/resolutions/16000
data/hic/cooler_files/wt_Rep1_2kb.mcool::/resolutions/32000
data/hic/cooler_files/wt_Rep1_2kb.mcool::/resolutions/64000
data/hic/cooler_files/wt_Rep1_2kb.mcool::/resolutions/128000
data/hic/cooler_files/wt_Rep1_2kb.mcool::/resolutions/256000
data/hic/cooler_files/wt_Rep1_2kb.mcool::/resolutions/512000
data/hic/cooler_files/wt_Rep1_2kb.mcool::/resolutions/1024000
```

I've just updated `mustache` using `pip` and I now get a different error:

```
The distance limit is set to 2Mbp
Reading contact map...
Traceback (most recent call last):
  File "/home/research/vaquerizas/liz/project/project_venv/lib/python3.8/site-packages/cooler/api.py", line 94, in _refresh
    grp = h5[self.root]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/research/vaquerizas/liz/project/project_venv/lib/python3.8/site-packages/h5py/_hl/group.py", line 288, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object '7' doesn't exist)"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/research/vaquerizas/liz/project/project_venv/bin/mustache", line 8, in <module>
    sys.exit(main())
  File "/home/research/vaquerizas/liz/project/project_venv/lib/python3.8/site-packages/mustache/mustache.py", line 923, in main
    o = regulator(f, args.norm_method, CHRM_SIZE, args.outdir,
  File "/home/research/vaquerizas/liz/project/project_venv/lib/python3.8/site-packages/mustache/mustache.py", line 792, in regulator
    x, y, v = read_mcooler(f, distance_in_bp, chromosome,chromosome2, res)
  File "/home/research/vaquerizas/liz/project/project_venv/lib/python3.8/site-packages/mustache/mustache.py", line 451, in read_mcooler
    clr = cooler.Cooler(uri)
  File "/home/research/vaquerizas/liz/project/project_venv/lib/python3.8/site-packages/cooler/api.py", line 89, in __init__
    self._refresh()
  File "/home/research/vaquerizas/liz/project/project_venv/lib/python3.8/site-packages/cooler/api.py", line 110, in _refresh
    raise KeyError(err_msg)
KeyError: "No cooler found at: data/hic/cooler_files/project_Rep1_2kb.mcool. Coolers found in ['/resolutions/2000', '/resolutions/4000', '/resolutions/8000', '/resolutions/16000', '/resolutions/32000', '/resolutions/64000', '/resolutions/128000', '/resolutions/256000', '/resolutions/512000', '/resolutions/1024000']. Use '::' to specify a group path"
```

Before, I was able to use the cooler file without specifying the resolution like `project_Rep1_2kb.mcool::/resolutions/2000` -- should I now be specifying the resolution to use from the cooler file there as well as in the resolution argument to `mustache`?

**Comment by ay-lab** [comment]
Sorry, my bad. I had to change the read_mcooler() function to be able to read from that old mcool file but I forgot to change it back. Please try again.

**Comment by liz-is** [comment]
It's working now, thanks a lot! I haven't inspected the loop calls in detail yet, but they look reasonable at a glance, so I'll close this now.
