### ISSUE TITLE
Genomic region out of bounds

### ISSUE THREAD

**Issue by EmmanuelCzt** [ay-lab/mustache#15]
Hi,

I'm trying to use mustache to call for significant loops on a ICE balanced contact matrix from a capture HiC experiment targeting a 3Mb locus. I installed mustache throught conda. Here's the command I used :

`mustache -f capHiC_iced_5kb.cool -ch chrX -r 5kb -pt 0.05 -cz hg38chrom.sizes  -o out_capHiC_iced_5kb.tsv`

and the error message I get : 

The distance limit is set to 2Mbp
Reading contact map...
8000000 18000000
16000000 26000000
24000000 34000000
32000000 42000000
40000000 50000000
48000000 58000000
56000000 66000000
64000000 74000000
64000000 74000000
72000000 82000000
88000000 98000000
96000000 106000000
104000000 114000000
112000000 122000000
120000000 130000000
128000000 138000000
136000000 146000000
144000000 154000000
152000000 162000000
Traceback (most recent call last):
  File "/home/emmanuel/miniconda3/envs/mustache/bin/mustache", line 8, in <module>
    sys.exit(main())
  File "/home/emmanuel/miniconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 966, in main
    o = regulator(f, args.norm_method, CHRM_SIZE, args.outdir,
  File "/home/emmanuel/miniconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 795, in regulator
    x, y, v, res = read_cooler(f, distance_in_bp, chromosome,chromosome2)
  File "/home/emmanuel/miniconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 396, in read_cooler
    temp = clr.matrix(balance=True,sparse=True).fetch( (chr1, int(start), int(end)))
  File "/home/emmanuel/miniconda3/envs/mustache/lib/python3.8/site-packages/cooler/core.py", line 573, in fetch
    i0, i1, j0, j1 = self._fetch(*args, **kwargs)
  File "/home/emmanuel/miniconda3/envs/mustache/lib/python3.8/site-packages/cooler/api.py", line 384, in _fetch
    region1 = parse_region(region, self._chromsizes)
  File "/home/emmanuel/miniconda3/envs/mustache/lib/python3.8/site-packages/cooler/util.py", line 181, in parse_region
    raise ValueError("Genomic region out of bounds: [{}, {})".format(start, end))
ValueError: Genomic region out of bounds: [152000000, 162000000)

The way I understand it, is that mustache finds X-linked data beyond the annotated size of the chrX (156040895 bp) but I check with cooler dump there is contact frequencies for my captured locus and only for this locus. Do you have a more precise idea of what's going on and how to solve it ? 

Cheers,

Emmanuel

**Comment by EmmanuelCzt** [comment]
Hi @ay-lab, thanks for the prompt reply ! 
As you suggested :  `mustache -f capHiC_iced_5kb.cool -ch chrX -r 5kb -pt 0.05 -o out_capHiC_iced_5kb.tsv`

and the output : 

The distance limit is set to 2Mbp
Reading contact map...
8000000 18000000
16000000 26000000
24000000 34000000
32000000 42000000
40000000 50000000
48000000 58000000
56000000 66000000
64000000 74000000
64000000 74000000
72000000 82000000
88000000 98000000
96000000 106000000
104000000 114000000
112000000 122000000
120000000 130000000
128000000 138000000
136000000 146000000
144000000 154000000
152000000 162000000
Traceback (most recent call last):
  File "/home/emmanuel/miniconda3/envs/mustache/bin/mustache", line 8, in <module>
    sys.exit(main())
  File "/home/emmanuel/miniconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 966, in main
    o = regulator(f, args.norm_method, CHRM_SIZE, args.outdir,
  File "/home/emmanuel/miniconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 795, in regulator
    x, y, v, res = read_cooler(f, distance_in_bp, chromosome,chromosome2)
  File "/home/emmanuel/miniconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 396, in read_cooler
    temp = clr.matrix(balance=True,sparse=True).fetch( (chr1, int(start), int(end)))
  File "/home/emmanuel/miniconda3/envs/mustache/lib/python3.8/site-packages/cooler/core.py", line 573, in fetch
    i0, i1, j0, j1 = self._fetch(*args, **kwargs)
  File "/home/emmanuel/miniconda3/envs/mustache/lib/python3.8/site-packages/cooler/api.py", line 384, in _fetch
    region1 = parse_region(region, self._chromsizes)
  File "/home/emmanuel/miniconda3/envs/mustache/lib/python3.8/site-packages/cooler/util.py", line 181, in parse_region
    raise ValueError("Genomic region out of bounds: [{}, {})".format(start, end))
ValueError: Genomic region out of bounds: [152000000, 162000000)

For the record, I ran mustache to check my installation on the data and the command line displayed in the expample 3 of your wiki and I didn't get any error message. I ran it as well on the same data but for chr1 and chr12 in order to check if I obtained the same loops as the fig3 and 4 of your paper and I exactly reproduced your results.

**Comment by ay-lab** [comment]
It's weird. Mustache gets the chromosome names and their sizes directly from the .cool file. This error is actually saying that the .cool file is giving a size bigger than the actual size of the chrX matrix it has! Can you share some data so I can reproduce the error?

**Comment by ay-lab** [comment]
It should be fixed now. Please try again and let me know if it works now.

**Comment by EmmanuelCzt** [comment]
After making a new conda env with the new version, mustache ran without errors with both of the above command line and the results are coherent with the contact map. 

Thanks a lot for your help !
