### ISSUE TITLE
mustache crashing on human chrY in newly created .cool file

### ISSUE THREAD

**Issue by mblanche** [ay-lab/mustache#17]
Hi, I'm running mustache how of a freshly made docker image where I installed only mustache using pip3. Mustache runs fine expect for chrY. Any chance you could fix that issue? It's a problem for what we try to achieve.

Here's a report with an example crashing.

Problem:
mustache is crashing when processing chrY

How to reproduce:
```
wget https://dovetail-public.s3-us-west-2.amazonaws.com/publicData/mustacheEx/test.cool
docker  run -v ${PWD}:/mnt -i mblanche/mustache mustache -p 24 -f /mnt/test.cool  -r 5kb -ch chrY -o test_chrY.tsv
```

Error generated:
```
The distance limit is set to 2Mbp
Reading contact map...
0 4000000.0
2000000.0 6000000.0
4000000.0 8000000.0
6000000.0 10000000.0
8000000.0 12000000.0
10000000.0 14000000.0
12000000.0 16000000.0
14000000.0 18000000.0
16000000.0 20000000.0
18000000.0 22000000.0
22000000.0 26000000.0
24000000.0 28000000.0
24000000.0 28000000.0
26000000.0 30000000.0
30000000.0 34000000.0
32000000.0 36000000.0
34000000.0 38000000.0
36000000.0 40000000.0
38000000.0 42000000.0
40000000.0 44000000.0
42000000.0 46000000.0
44000000.0 48000000.0
46000000.0 50000000.0
48000000.0 52000000.0
50000000.0 54000000.0
52000000.0 56000000.0
54000000.0 58000000.0
Traceback (most recent call last):
  File "/usr/local/bin/mustache", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/mustache/mustache.py", line 966, in main
    o = regulator(f, args.norm_method, CHRM_SIZE, args.outdir,
  File "/usr/local/lib/python3.8/dist-packages/mustache/mustache.py", line 795, in regulator
    x, y, v, res = read_cooler(f, distance_in_bp, chromosome,chromosome2)
  File "/usr/local/lib/python3.8/dist-packages/mustache/mustache.py", line 396, in read_cooler
    temp = clr.matrix(balance=True,sparse=True).fetch( (chr1, int(start), int(end)))
  File "/usr/local/lib/python3.8/dist-packages/cooler/core.py", line 573, in fetch
    i0, i1, j0, j1 = self._fetch(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/cooler/api.py", line 384, in _fetch
    region1 = parse_region(region, self._chromsizes)
  File "/usr/local/lib/python3.8/dist-packages/cooler/util.py", line 181, in parse_region
    raise ValueError("Genomic region out of bounds: [{}, {})".format(start, end))
ValueError: Genomic region out of bounds: [54000000, 58000000)
```

Dockerfile use to generate the image container:
```
FROM ubuntu:20.04

USER root

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y\
    && DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y \
    python3 \
    python3-pip \
    && pip3 install \
    mustache-hic \
    && apt-get clean \
    && apt-get purge \
    && rm -rf /var/lib/apt/lists/* /tmp/*
```

**Comment by ay-lab** [comment]
Hi, thanks for using our tool. I'll fix that in a few hours and will update the code.

**Comment by ay-lab** [comment]
I updated the code.

**Comment by mblanche** [comment]
Thanks a lot! I see that it’s updated on pypi as well, I’ll rebuild my image and make sure it has the new version. 

Best

Sent from my iPad

-- Marco
