### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by xinyangbing** [ay-lab/mustache#2]
Hi,
Thanks for the tool! I tried running it on a Micro-C dataset, at 500bp resolution, but run into problems with a huge amount of memory requested (#SBATCH --mem=240000 --cpus-per-task=24)
"""
Reading contact map...
Traceback (most recent call last):
  File "./mustache/mustache/mustache.py", line 613, in <module>
    main()
  File "./mustache/mustache/mustache.py", line 591, in main
    o = regulator(f, args.outdir,
  File "./mustache/mustache/mustache.py", line 507, in regulator
    c, n = read_cooler(f, chromosome)
  File "./mustache/mustache/mustache.py", line 252, in read_cooler
    result = clr.matrix(balance=True).fetch(chr)
  File "/Genomics/grid/users/xbing/miniconda3/envs/mustache/lib/python3.8/site-packages/cooler/core.py", line 574, i
n fetch
    return self._slice(self.field, i0, i1, j0, j1)
  File "/Genomics/grid/users/xbing/miniconda3/envs/mustache/lib/python3.8/site-packages/cooler/api.py", line 362, in
 _slice
    return matrix(
  File "/Genomics/grid/users/xbing/miniconda3/envs/mustache/lib/python3.8/site-packages/cooler/api.py", line 746, in
 matrix
    arr = arr * np.outer(bias1, bias2)
  File "<__array_function__ internals>", line 5, in outer
  File "/Genomics/grid/users/xbing/miniconda3/envs/mustache/lib/python3.8/site-packages/numpy/core/numeric.py", line
 906, in outer
    return multiply(a.ravel()[:, newaxis], b.ravel()[newaxis, :], out)
MemoryError: Unable to allocate 412. GiB for an array with shape (235138, 235138) and data type float64
"""
What can you suggest I do?

**Comment by ay-lab** [comment]
Hi, please try the updated code. We haven't run mustache on 500bp resolution, so, please let us know how it works for you.
