### ISSUE TITLE
diff_mustache.py crashing on input file format

### ISSUE THREAD

**Issue by esebesty** [ay-lab/mustache#25]
I'm trying to run `diff_mustache.py` on two `hic` files with the example command line, and getting the following error:

```
The distance limit is set to 2000000bp
Traceback (most recent call last):
  File "/home/user2031/work/repos/bcro/bit-bio/mustache/mustache/diff_mustache.py", line 1438, in <module>
    main()
  File "/home/user2031/work/repos/bcro/bit-bio/mustache/mustache/diff_mustache.py", line 1323, in main
    chrs, resolutions, masterindex, genome, metadata = read_header(hic)
  File "/home/user2031/work/repos/bcro/bit-bio/mustache/mustache/diff_mustache.py", line 277, in read_header
    key = readcstr(req)
  File "/home/user2031/work/repos/bcro/bit-bio/mustache/mustache/diff_mustache.py", line 237, in readcstr
    return buf.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte
```

Looks like the `hic` format is wrong. I tried to use the `allValidPairs` output of HiC-Pro, converted with Juicer. Should I use something else?

**Comment by esebesty** [comment]
I used the hic file, converted with juicer_tools.2.10.01.jar.

**Comment by ay-lab** [comment]
I see, I haven't tried the version 2 yet but I will soon. Do you have any .hic files from older versions of juicer to see if you get a similar error or not ("https://github.com/aidenlab/juicer/wiki/Download")?
