### ISSUE TITLE
Strange error from diff-mustache

### ISSUE THREAD

**Issue by gabedolpten** [ay-lab/mustache#27]
Hi, I am running mustache with the following parameters and I get this error:

Traceback (most recent call last):
  File "/Genomics/grid/users/gdolsten/.conda/envs/mustache/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Genomics/grid/users/gdolsten/.conda/envs/mustache/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "./github_mustache/mustache/diff_mustache.py", line 1230, in process_block
    loops1, diff_loops1, loops2, diff_loops2 = diff_mustache(
ValueError: not enough values to unpack (expected 4, got 0)

Do you know what the source of this is?

**Comment by batzza** [comment]
Just wanted to report I get the same error printed to terminal several times while running diff_mustache. Below is a snippet of the error in context.

`$ python3.8 diff_mustache.py -f1 D060.hic -f2 D070.hic -p 25 -pt 0.05 -pt2 0.05 -o D060vD070_loops_mustache.tsv -r 5000


The distance limit is set to 2Mbp
Reading contact map...
0 16569
HiC version:  8
0 16569
HiC version:  8
Normalizing contact map...
Loop calling...
Starting block 1/1...
Process Process-2:
Traceback (most recent call last):
  File "/data/batzza/conda/envs/mustache/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/batzza/conda/envs/mustache/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "Tools/mustache/mustache/diff_mustache.py", line 1134, in process_block
    loops1, diff_loops1, loops2, diff_loops2 = diff_mustache(
ValueError: not enough values to unpack (expected 4, got 0)
0 loops found for chrmosome=M, fdr<0.05 in 0.87sec
Reading contact map...

[...]

HiC version:  8
0 10000000
HiC version:  8
8000000 18000000
HiC version:  8
16000000 26000000
HiC version:  8
24000000 34000000
HiC version:  8
32000000 42000000
HiC version:  8
40000000 50000000
HiC version:  8
48000000 58000000
HiC version:  8
56000000 66000000
HiC version:  8
64000000 74000000
HiC version:  8
72000000 82000000
HiC version:  8
80000000 90000000
HiC version:  8
88000000 98000000
HiC version:  8
96000000 101991188
HiC version:  8
Normalizing contact map...
Loop calling...
Starting block 1/13...
Process Process-310:
Starting block 2/13...
Traceback (most recent call last):
  File "/data/batzza/conda/envs/mustache/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/batzza/conda/envs/mustache/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "Tools/mustache/mustache/diff_mustache.py", line 1134, in process_block
    loops1, diff_loops1, loops2, diff_loops2 = diff_mustache(
ValueError: not enough values to unpack (expected 4, got 0)
Process Process-311:
Traceback (most recent call last):
  File "/data/batzza/conda/envs/mustache/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/batzza/conda/envs/mustache/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "Tools/mustache/mustache/diff_mustache.py", line 1134, in process_block
    loops1, diff_loops1, loops2, diff_loops2 = diff_mustache(
ValueError: not enough values to unpack (expected 4, got 0)
Starting block 3/13...
Starting block 4/13...
Starting block 5/13...
Starting block 6/13...
Starting block 7/13...
Starting block 8/13...
Starting block 9/13...
Starting block 10/13...
Starting block 11/13...
Starting block 12/13...
Starting block 13/13...
Block 3 done.
Block 6 done.
Block 8 done.
Block 11 done.
Block 12 done.
Block 9 done.
Block 4 done.
Block 10 done.
Block 5 done.
Block 7 done.
Block 13 done.
(406,454) loops and (122,212) differential-loops found in chrmosome=15 for detection-fdr<0.05 and difference-fdr<0.05 in 100.09sec`

**Comment by ay-lab** [comment]
Hi, it should be fixed now.

**Comment by batzza** [comment]
Yes, seems to be working thanks! However, I encountered a new error that I will post about separately.
