### ISSUE TITLE
Differential loop calling with .cool rather than .hic

### ISSUE THREAD

**Issue by keoughkath** [ay-lab/mustache#28]
Hello, is the differential loop tool intended to work with .cool files or only .hic? I ask because when I input .cool files, I get this error: 

```
Traceback (most recent call last):
  File "./mustache/mustache/diff_mustache.py", line 1342, in <module>
    main()
  File "./mustache/mustache/diff_mustache.py", line 1270, in main
    o = regulator(f1, f2, args.norm_method, CHRM_SIZE, args.outdir,
  File "./mustache/mustache/diff_mustache.py", line 1037, in regulator
    x1, y1, v1, res = read_cooler(f1, distance_in_bp, chromosome,chromosome2, norm_method)
NameError: name 'read_cooler' is not defined
```

**Comment by roayaei** [comment]
Hi, sorry, no, the function was deleted by accident. It should work now.

**Comment by keoughkath** [comment]
Great, thanks!
