### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by pna059** [ay-lab/mustache#30]
Hi, 
I am running Mustache:
$ mustache -f inter_1to10kb.hic -r 10kb -st 0.7 -pt 0.1 -o10kb_loops.tsv

....after running smoothly over the chromosomes, I am getting an error. I am still getting some loops called, but it seems incomplete
......
Reading contact map...
0 32268
HiC version:  8
Normalizing contact map...
Loop calling...
Starting block 1/1...
Block 1 done.
0 loops found for chrmosome=HIC_SCAFFOLD_74, fdr<0.1 in 108.90sec
Reading contact map...
0 6124
HiC version:  8
File doesn't have the given chr_chr map

File did not contain KR normalization vectors for one or both chromosomes at 10000 BP

HiC version:  8
File doesn't have the given chr_chr map

File did not contain VC normalization vectors for one or both chromosomes at 10000 BP

Traceback (most recent call last):
  File "/home/pavlan/.conda/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 396, in read_hic_file
    temp = straw.straw("KR", f, str(chr1)+":"+str(int(start))+":"+str(int(end)),  str(chr2)+":"+str(int(start))+":"+str(int(end)), "BP", res)
  File "/home/pavlan/.conda/envs/mustache/lib/python3.8/site-packages/straw/straw.py", line 511, in straw
    myFilePos=list1[0]
TypeError: 'int' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pavlan/.conda/envs/mustache/bin/mustache", line 8, in <module>
    sys.exit(main())
  File "/home/pavlan/.conda/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 1137, in main
    o = regulator(f, args.norm_method, CHRM_SIZE, args.outdir,
  File "/home/pavlan/.conda/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 948, in regulator
    x, y, v = read_hic_file(f, norm_method, CHRM_SIZE, distance_in_bp, chromosome,chromosome2, res)
  File "/home/pavlan/.conda/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 426, in read_hic_file
    temp = straw.straw("VC", f, str(chr1)+":"+str(int(start))+":"+str(int(end)),  str(chr2)+":"+str(int(start))+":"+str(int(end)), "BP", res)
  File "/home/pavlan/.conda/envs/mustache/lib/python3.8/site-packages/straw/straw.py", line 511, in straw
    myFilePos=list1[0]
TypeError: 'int' object is not subscriptable

**Comment by ay-lab** [comment]
If your chromosomes are sorted based on size then you should be fine. I think the error is happening for your small chromosomes due to their different name formats. I'll fix that in the next update. For now you can input only the chromosomes you want to run mustache on by "-ch chr1_name chr2_name ....".
