### ISSUE TITLE
no module named 'straw'

### ISSUE THREAD

**Issue by ccmeth** [ay-lab/mustache#40]
Hi,

Recently I decided to use this package to identify chromatin loops, and when I run this command ( python3 ./mustache/mustache/mustache.py  -f ./mustache/data/chr21_5kb.RAWobserved -b ./mustache/data/chr21_5kb.KRnorm -ch 21 -r 5kb -o chr21_out5.tsv -pt 0.1 -st 0.8 ), an error (no module named straw) appeared.  Then I installed the hic-straw through pip, however, this error was not solved.

Could you please tell me how to solve this issue?

**Comment by mblanche** [comment]
Hi guys, same problem here. I have installed both straw-hic from the Aiden lab and mustache-hic from you using pip3 in a docker image I'm building and I'm getting the same error:

```
$ docker run -it dovetailg/mustache mustache -h
Traceback (most recent call last):
  File "/usr/local/bin/mustache", line 5, in <module>
    from mustache.mustache import main
  File "/usr/local/lib/python3.8/dist-packages/mustache/mustache.py", line 14, in <module>
    import straw
ModuleNotFoundError: No module named 'straw'
```

Any help here? I think it's a problem from the straw module itself...

**Comment by mblanche** [comment]
Hey guys, line 14 of https://github.com/ay-lab/mustache/blob/master/mustache/mustache.py

from [pypi hic-straw](https://pypi.org/project/hic-straw/), the import should be `import hicstraw`

Could you push a quick hotfix?

**Comment by ay-lab** [comment]
I thought we had accepted that pull request but seems like we didn't. I accepted it now. Please let us know if that works.
Abbas will review it further to make sure everything works fine.

**Comment by ay-lab** [comment]
Yes. I believe everyone needs to update the hic-straw now: "pip install hic-straw==1.3.0"

**Comment by mblanche** [comment]
Sorry, my question was whether your were planning on updating mustach-hic release to the latest version on pypi. Makes handling docker build easier! 

Sent from my iPad

-- Marco

**Comment by ay-lab** [comment]
yes, mustache pypi is updated to 1.2.5.

**Comment by mblanche** [comment]
Great! Will update the docker image, restart the pipeline and let you know how it goes. 

Best,

Marco

**Comment by ccmeth** [comment]
> Hey guys, line 14 of https://github.com/ay-lab/mustache/blob/master/mustache/mustache.py
> 
> from [pypi hic-straw](https://pypi.org/project/hic-straw/), the import should be `import hicstraw`
> 
> Could you push a quick hotfix?

Thanks for your suggestion! Based on this, the issue has been solved.
