### ISSUE TITLE
differential loop analysis

### ISSUE THREAD

**Issue by TerezaClarence** [ay-lab/mustache#41]
Dear developers of Mustache,

thank you for this interesting tool. I would like to run differential analysis on 2 hic samples but I tend to get error:

```
$ mustache -f1 sample1.hic -f2 sample2.hic -r 25000 -pt 0.05 -pt2 0.05 -o output
usage: mustache [-h] [-f F_PATH] [-d DISTFILTER] -o OUTDIR -r RESOLUTION [-bed BED] [-m MAT] [-b BIASFILE] [-cz CHRSIZE_FILE] [-norm NORM_METHOD] [-st ST] [-pt PT]
                [-sz S_Z] [-oc OCTAVES] [-i S] [-p NPROCESSES] [-ch CHROMOSOME [CHROMOSOME ...]] [-ch2 CHROMOSOME2 [CHROMOSOME2 ...]] [-v VERBOSE]
mustache: error: argument -p/--processes: invalid int value: 't2'
```
Can you please help me to debug?

Thank you very much.

Best,
Tereza

**Comment by TerezaClarence** [comment]
Thank you so much for such a swift reply! I have a problem with the above again; I activate my mustache env via conda activate mustache (following your installation tutorial) and then:

`mustache/mustache/diff_mustache.py -f1 sample1.hic -f2 sample2.hic -pt 0.05 -pt2 0.05 -o output -r 25000
Traceback (most recent call last):
  File "mustache/mustache/diff_mustache.py", line 12, in <module>
    import pandas as pd
  File "/hpc/users/XXXX/.local/lib/python3.8/site-packages/pandas/__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
dateutil: No module named 'dateutil'
`
I was trying to update pandas and dateutil but doesn't help. Is there something I can do to fix this?


Many thanks,
Tereza

**Comment by ay-lab** [comment]
Seems like the issue is diff_mustache is still trying to use the old hic straw. We should be able to fix this soon

**Comment by TerezaClarence** [comment]
thank you so much!

**Comment by ay-lab** [comment]
should be fixed now. Let me know how it goes.

**Comment by ccmeth** [comment]
> should be fixed now. Let me know how it goes.

Thanks for providing such a useful tool! So based on the above communication, the mustache installed via pip3 does not have the diff_mustache function?

**Comment by roayaei** [comment]
Did you face any problem? Both mustache and diff_mustache should work.

**Comment by DittmanC** [comment]
diff_mustache.py [-h] [-f1 F_PATH1] [-f2 F_PATH2] [-d DISTFILTER] -o OUTDIR -r RESOLUTION [-bed1 BED1] [-m1 MAT1] [-b1 BIASFILE1] [-bed2 BED2] [-m2 MAT2]
                        [-b2 BIASFILE2] [-cz CHRSIZE_FILE] [-norm NORM_METHOD] [-st ST] [-pt PT] [-pt2 PT2] [-sz S_Z] [-oc OCTAVES] [-i S] [-p NPROCESSES]
                        [-ch CHROMOSOME [CHROMOSOME ...]] [-ch2 CHROMOSOME2 [CHROMOSOME2 ...]] [-v VERBOSE]

Is there any detail description for this command? what do -pt2 and -oc mean ? Thanks
