### ISSUE TITLE
issue using diff_mustache with .mcools

### ISSUE THREAD

**Issue by Elphege-Nora** [ay-lab/mustache#45]
Thank you for a great software.

I am unable to run diff_mustache.py with .mcool files as input (no problem running mustache.py on the same files)

`python3 ./mustache/mustache/diff_mustache.py -f1 file1.mcool -f2 file2.mcool -pt 0.1 -pt2 0.1 -o output -r 10000 -st 0.8`

gives me 

```
Reading contact map...
Traceback (most recent call last):
  File "./mustache/diff_mustache.py", line 910, in <module>
    main()
  File "./mustache/diff_mustache.py", line 838, in main
    o = regulator(f1, f2, args.norm_method, CHRM_SIZE, args.outdir,
  File "./mustache/diff_mustache.py", line 607, in regulator
    x1, y1, v1 = read_mcooler(f1, distance_in_bp, chromosome,chromosome2, res, norm_method)
NameError: name 'read_mcooler' is not defined
```

do I need to declare the .mcool files differently?
Many thanks in advance!

**Comment by ay-lab** [comment]
Thanks for pointing out the issue. Should be fixed now.
