### ISSUE TITLE
Interchromosomal analysis

### ISSUE THREAD

**Issue by ycliangtaiwan** [ay-lab/mustache#46]
Thank you for developing this great tool. I am currently doing interchromosomal analysis using a command:

**$ mustache -f MiC-5_merged.mapped.gg7w.chr.contact_map.hic -ch chr14 -ch2 chr17 -r 10kb -o result_trans-loop_14+17_10kb.tsv**

But it keeps showing:
NameError: name 'inter_normalize_map' is not defined

I tried different parameters and looked into the .py file:
    **else:
        n1 = max(x) + 1
        n2 = max(y) + 1
        inter_normalize_map(v)**

I also tried to use .cool file but it showed different errors... 
I don't know how to resolve the issue. Please give me a hint.

Many thanks,

Ya-Chen

------
**# the full output of using a .hic file is as the following:**

$ mustache -f MiC-5_merged.mapped.gg7w.chr.contact_map.hic -ch chr14 -ch2 chr17 -r 10kb -o result_trans-loop_14+17_10kb.tsv

The distance limit is set to 2000000bp
Reading contact map...
0 15370873
HiC version:  8
Normalizing contact map...
Traceback (most recent call last):
  File "/home/galaxy/anaconda2/envs/mustache/bin/mustache", line 8, in <module>
    sys.exit(main())
  File "/home/galaxy/anaconda2/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 1137, in main
    o = regulator(f, args.norm_method, CHRM_SIZE, args.outdir,
  File "/home/galaxy/anaconda2/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 1009, in regulator
    inter_normalize_map(v)
NameError: name 'inter_normalize_map' is not defined

----
**# the full output of using a .cool file is as the following:**

$ mustache -f MiC-5_merged.mapped.gg6ens.matrix_1kb.cool -ch 14 -ch2 17 -r 10kb -p 8 -d balance=False -o mic_our_trans-loop_MiC-5_ch14+17_10kb_p0.1.tsv

The distance limit is set to 2000000bp
Reading contact map...
Your cooler data resolution is 1000
Traceback (most recent call last):
  File "/home/galaxy/anaconda2/envs/mustache/bin/mustache", line 8, in <module>
    sys.exit(main())
  File "/home/galaxy/anaconda2/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 1137, in main
    o = regulator(f, args.norm_method, CHRM_SIZE, args.outdir,
  File "/home/galaxy/anaconda2/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 950, in regulator
    x, y, v, res = read_cooler(f, distance_in_bp, chromosome,chromosome2, norm_method)
  File "/home/galaxy/anaconda2/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 540, in read_cooler
    result = clr.matrix(balance=True,sparse=True).fetch(chr1, chr2)
  File "/home/galaxy/.local/lib/python3.8/site-packages/cooler/core.py", line 574, in fetch
    return self._slice(self.field, i0, i1, j0, j1)
  File "/home/galaxy/.local/lib/python3.8/site-packages/cooler/api.py", line 362, in _slice
    return matrix(
  File "/home/galaxy/.local/lib/python3.8/site-packages/cooler/api.py", line 684, in matrix
    raise ValueError(
ValueError: No column 'bins/weight'found. Use ``cooler.balance_cooler`` to calculate balancing weights or set balance=False.

**Comment by roayaei** [comment]
Hi Ya-Chen, unfortunately mustache doesn't support inter-chromosomal but you don't really need a complex method for calling loops in inter-chromosomal . You can simply use the z-score and threshold on that.

**Comment by ay-lab** [comment]
For that, you can simply use FitHiC2 to assign p-values and then stringently filter for the types of pixels you want. https://github.com/ay-lab/fithic

**Comment by ycliangtaiwan** [comment]
Thank you so much, roayaei and ay-lab. I was trying Cooler dump with balance but still not sure if the interchromosomal interactions are significant.
The FitHiC2 looks great (and wet-bench scientist friendly), I'm going to give it a try.
Many thanks,
