### ISSUE TITLE
generate this errors, do you know if it's my .hic file has some problem

### ISSUE THREAD

**Issue by Lattesnow** [ay-lab/mustache#52]
the test data is okay
for my own .hic data this is what i got 

The distance limit is set to 2000000bp
Reading contact map...
0 4000000
HiC version:  8
HiC version:  8
Traceback (most recent call last):
  File "/home/snow/anaconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 396, in read_hic_file
    temp = straw.straw("KR", f, str(chr1)+":"+str(int(start))+":"+str(int(end)),  str(chr2)+":"+str(int(start))+":"+str(int(end)), "BP", res)
  File "/home/snow/anaconda3/envs/mustache/lib/python3.8/site-packages/straw/straw.py", line 510, in straw
    list1 = readFooter(req, c1, c2, norm, unit, binsize)
  File "/home/snow/anaconda3/envs/mustache/lib/python3.8/site-packages/straw/straw.py", line 158, in readFooter
    nExpectedValues = struct.unpack('<i',req.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/snow/anaconda3/envs/mustache/bin/mustache", line 11, in <module>
    sys.exit(main())
  File "/home/snow/anaconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 1137, in main
    o = regulator(f, args.norm_method, CHRM_SIZE, args.outdir,
  File "/home/snow/anaconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 948, in regulator
    x, y, v = read_hic_file(f, norm_method, CHRM_SIZE, distance_in_bp, chromosome,chromosome2, res)
  File "/home/snow/anaconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 426, in read_hic_file
    temp = straw.straw("VC", f, str(chr1)+":"+str(int(start))+":"+str(int(end)),  str(chr2)+":"+str(int(start))+":"+str(int(end)), "BP", res)
  File "/home/snow/anaconda3/envs/mustache/lib/python3.8/site-packages/straw/straw.py", line 510, in straw
    list1 = readFooter(req, c1, c2, norm, unit, binsize)
  File "/home/snow/anaconda3/envs/mustache/lib/python3.8/site-packages/straw/straw.py", line 158, in readFooter
    nExpectedValues = struct.unpack('<i',req.read(4))[0]
struct.error: unpack requires a buffer of 4 bytes

**Comment by roayaei** [comment]
are you using the last version (1.3.1)?

**Comment by Lattesnow** [comment]
> are you using the last version (1.3.1)?

I am not sure. I downloaded mustache through conda install mustache-hic

**Comment by ay-lab** [comment]
then just do "pip install mustache-hic==1.3.1" in your mustache conda environment and run mustache again.

**Comment by Lattesnow** [comment]
> then just do "pip install mustache-hic==1.3.1" in your mustache conda environment and run mustache again.

what is the right python version for mustache? the instruction on python version in conda install made me confused. 
Thank you for all the help.

**Comment by roayaei** [comment]
I think anything above 3.6 should work.

**Comment by Lattesnow** [comment]
Thanks for making it clear. 
Another question is for the diff function. Does it only support the .hic format?

**Comment by ay-lab** [comment]
No, it supports .cool too.

**Comment by Lattesnow** [comment]
> No, it supports .cool too.

got it running without any problem now. Thanks for all the replies
