### ISSUE TITLE
Mustache : IndexError: list index out of range 

### ISSUE THREAD

**Issue by FCamera** [ay-lab/mustache#68]
I am using Mustache to call loops on MICRO-C data mapped on human genome T2T version (CHM13/hs1)
I run each chromosome individually with this code:

E.g. For chromosome 1
mustache -f <map.hic file> -ch chr1 -r 5kb -st 0.7 -o <.tsv file>

It works for all the chromosomes except for chr9, chr15, chr16, chr21, and chrY. For these chromosomes I get the following error:

The distance limit is set to 2Mbp
Reading contact map...
0 10000000
8000000 18000000
16000000 26000000
24000000 34000000
32000000 42000000
40000000 50000000
48000000 58000000
56000000 66000000
64000000 74000000
72000000 82000000
80000000 90000000
88000000 98000000
96000000 99753194
Traceback (most recent call last):
  File "/.conda/envs/mustache/bin/mustache", line 11, in <module>
    sys.exit(main())
  File "/.conda/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 1057, in main
    o = regulator(f, args.norm_method, CHRM_SIZE, args.outdir,
  File "/.conda/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 870, in regulator
    x, y, v = read_hic_file(f, norm_method, CHRM_SIZE, distance_in_bp, chromosome, chromosome2, res)
  File "/.conda/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 359, in read_hic_file
    x = np.array(result[0]) // res
IndexError: list index out of range

I was wondering if I could get some help with this,
Thanks a lot and regards,
Francesco.

**Comment by cemilcan98** [comment]
Hi Francesco,

The latest update on mustache.py should be taking care of this issue, can you check if you are using the latest code? Please let me know if that helps and works
