### ISSUE TITLE
resolution

### ISSUE THREAD

**Issue by ningwei-wei** [ay-lab/mustache#8]
hi
your method looks useful. but i have a question aboult the resolution whether be set 500bp when i run mustache with hic data that is 1kb resolution?

i will appreciate if you can reply me quickly

**Comment by ay-lab** [comment]
Hi, thanks for using our tool. I am not sure if I understand your question. You have 1kb resolution data but you want to run mustache on 500bp resolution? You should first create your 500bp resolution data and then run mustache on it.

**Comment by ningwei-wei** [comment]
Hi,
 i am sorry about don't clear my question.
we know the map resolution of hic data is definded  the smallest locus size such that 80% of loci have at least 1,000 contacts.
so i think that when we set bin size in 500 bp, there maybe have less 80% of loci have at least 1,000 contacts under 1kb resolution data.
now i want to find the interaction region when bin size is 500 bp. so you think your method can do it?

**Comment by ningwei-wei** [comment]
hi ,
i also run my data with mustache
~~~shell
mustache -f ./GSM1551550_HIC001_30.hic -ch 1 -r 1kb -pt 0.01 -o hic_out.tsv


The distance limit is set to 2000000bp
Reading contact map...
HiC version:  8
File did not contain KR normalization vectors for one or both chromosomes at 1000 BP

HiC version:  8
File did not contain VC normalization vectors for one or both chromosomes at 1000 BP

Traceback (most recent call last):
  File "/public/slst/home/ningwei/anaconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 299, in read_hic_file
    result = straw.straw('KR', f, str(chr1), str(chr2), 'BP', res)  
  File "/public/slst/home/ningwei/anaconda3/envs/mustache/lib/python3.8/site-packages/straw/straw.py", line 511, in straw
    myFilePos=list1[0]
TypeError: 'int' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/public/slst/home/ningwei/anaconda3/envs/mustache/bin/mustache", line 8, in <module>
    sys.exit(main())
  File "/public/slst/home/ningwei/anaconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 904, in main
    o = regulator(f, args.norm_method, CHRM_SIZE, args.outdir,
  File "/public/slst/home/ningwei/anaconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 769, in regulator
    x, y, v = read_hic_file(f, norm_method, CHRM_SIZE, distance_in_bp, chromosome,chromosome2, res)
  File "/public/slst/home/ningwei/anaconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 301, in read_hic_file
    result = straw.straw('VC', f, str(chr1), str(chr2), 'BP', res)
  File "/public/slst/home/ningwei/anaconda3/envs/mustache/lib/python3.8/site-packages/straw/straw.py", line 511, in straw
    myFilePos=list1[0]
TypeError: 'int' object is not subscriptable
~~~

i don't know how to solve this problem. my 1kb hic data in https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM1551550

**Comment by ay-lab** [comment]
Your data ("GSM1551550_HIC001_30.hic") does not have 1kb resolution. I ran mustache for 5kb resolution and it worked fine.

**Comment by JHZ20** [comment]
Hi, 
I was wondering whether it is suitable to also use mustache to call loops at 25kb to 50kb resolutions?
