### ISSUE TITLE
TypeError on FitHiC input

### ISSUE THREAD

**Issue by auberginekenobi** [ay-lab/mustache#9]
Ran mustache on a sample using .hic format, worked fine for 5kb, 10kb, and 50kb resolution. The .hic file didn't have 25kb resolution, so I used HiC-Pro's hicpro2fithic.py to convert to FitHiC format. Error log follows:

```
/home/ochapman/miniconda3/envs/mustache/bin/mustache:8: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  sys.exit(main())


The distance limit is set to 2Mbp
Reading contact map...
Traceback (most recent call last):
  File "/home/ochapman/miniconda3/envs/mustache/bin/mustache", line 8, in <module>
    sys.exit(main())
  File "/home/ochapman/miniconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 904, in main
    o = regulator(f, args.norm_method, CHRM_SIZE, args.outdir,
  File "/home/ochapman/miniconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 775, in regulator
    x, y, v = read_pd(f, distance_in_bp, bias, chromosome, res)
  File "/home/ochapman/miniconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 249, in read_pd
    df = df[np.vectorize(is_chr)(df[0], chromosome)]
  File "/home/ochapman/miniconda3/envs/mustache/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2091, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/ochapman/miniconda3/envs/mustache/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2161, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/home/ochapman/miniconda3/envs/mustache/lib/python3.8/site-packages/numpy/lib/function_base.py", line 2121, in _get_ufunc_and_otypes
    outputs = func(*inputs)
  File "/home/ochapman/miniconda3/envs/mustache/lib/python3.8/site-packages/mustache/mustache.py", line 185, in is_chr
    return str(c) in re.findall("[1-9][0-9]*", s)
  File "/home/ochapman/miniconda3/envs/mustache/lib/python3.8/re.py", line 239, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
```
Input files:
```
(base) [ochapman@comet-14-01 input_25000]$ head fithic.interactionCounts
1       12500   1       187500  2
1       12500   1       54462500        1
1       12500   2       112500  1
1       12500   2       113587500       1
1       12500   2       194012500       1
1       12500   3       192862500       1
1       12500   4       487500  1
1       12500   6       115062500       1
1       12500   7       73687500        1
1       12500   7       112387500       1
```
```
(base) [ochapman@comet-14-01 input_25000]$ head fithic.biases
1       12500   0.0443452857034
1       37500   0.0180297825985
1       62500   0.250643862343
1       87500   0.248515390376
1       112500  0.316972901384
1       137500  0.177332034246
1       162500  -1
1       187500  0.212476913977
1       212500  0.0426961031691
1       237500  -1
```

**Comment by ay-lab** [comment]
Hi. Please try the updated code.
